spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: false
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
springdoc:
  swagger-ui:
    use-root-path: true
  version: 1.6.9
